title: "Building Performance Ruleset Data Schema"
author: "Big Ladder Software"
description: "A standardized data model for characterizing building performance rulesets"
colors:
  primary: "#b75532"
  secondary: "#608883"
  menu_text: "#fff"
