title: "Building Performance Ruleset Data Schema"
author: "Big Ladder Software"
description: "A standardized data model for characterizing building performance rulesets"
colors:
  primary: "#e6e6e6"
  secondary: "#d71e2e"
  menu_text: "#000"
